### PR TITLE
Add Maven Publish

### PR DESCRIPTION
**Pull request by JochenGuckSnk**
Adding maven publish to the luak library is relativly simple. But i am not able to test the change because the project has linking problems between the targets on my pc.

Possible fix for: #6

### CODE REVIEW

**Comment by Doomsdayrs** [comment]
The reason for the failing is what I can only assume is their non-standard Gradle architecture.

For example, disabling the `targetDesktop` does not actually remove the `native` source sets (which are broken as they depend on `common` but that is not setup properly as evidenced by InteliJ suggesting to add it as a dependency).

I was working on migrating the code back to standard gradle [here](https://gitlab.com/shosetsuorg/luak/-/tree/standard-gradle) but I lost interest due to having to work on other aspects of Shosetsu, College, and my Life.

Perhaps my work can help make it easier for you to get started with proper maven publishing.

**Comment by Doomsdayrs** [comment]
Update, my fork works completely now :D.

**Comment by soywiz** [comment]
Just out of curiosity, does JitPack publishes to common, jvm, js, android, ios, mingwX64, linuxX64, linuxArm64, macosX64, macosArm64, iosArm64, iosX64Simulator, watchosArm64, tvosArm64, wasm... and the rest of the variants artifacts?

**Comment by soywiz** [comment]
@JochenGuckSnk Maybe the fork of @Doomsdayrs works for you? What's the purpose of exposing maven publishing here?

**Comment by JochenGuckSnk** [comment]
@soywiz Yes the fork is working.

 From my perspective it makes no sense to have two projcects for the same thing just because of the build tools. I just want to use the library with vanilla gradle.(like @Doomsdayrs)

**Comment by soywiz** [comment]
I don't have any complaints about adding those lines here if it helps you. Thanks fro the PR!

**Comment by Doomsdayrs** [comment]
> @Doomsdayrs Just out of curiosity, does JitPack publishes to common, jvm, js, android, ios, mingwX64, linuxX64, linuxArm64, macosX64, macosArm64, iosArm64, iosX64Simulator, watchosArm64, tvosArm64, wasm... and the rest of the variants artifacts?

Yes

**Comment by soywiz** [comment]
@Doomsdayrs Can't see all those artifacts here: https://jitpack.io/com/gitlab/shosetsuorg/luak/ is JitPack building in a macos machine that is the only one supporting apple targets?

**Comment by soywiz** [comment]
Can't find anything about mac machines here: https://docs.jitpack.io/faq/#frequently-asked-questions

**Comment by Doomsdayrs** [comment]
> @Doomsdayrs Can't see all those artifacts here: https://jitpack.io/com/gitlab/shosetsuorg/luak/ is JitPack building in a macos machine that is the only one supporting apple targets?

https://jitpack.io/com/gitlab/shosetsuorg/luak/7ca543504c/build.log

**Comment by Doomsdayrs** [comment]
> Can't find anything about mac machines here: https://docs.jitpack.io/faq/#frequently-asked-questions where did you figured out that it supports macos, ios, watchos and tvos targets?

I haven't enabled cross compilation. I just got it working properly via standard gradle so I can at least use it in my application.

**Comment by Doomsdayrs** [comment]
> @Doomsdayrs `OS: Linux 4.14.63-xxxx-std-ipv6-64 amd64` <- https://jitpack.io/com/gitlab/shosetsuorg/luak/7ca543504c/build.log
> 
> A linux machine. Even if you enable macos, ios, tvos and watchos targets, it won't work.
> 
> That's the pity of Kotlin Multiplatform. Mac OS machines are needed to publish all the targets. I wished they had a binary format not relying on all the Apple infrastructure, and just requiring it for linking, or directly that it would be source-code-based or AST-based. And in fact kproject tries to fix that issue by doign source-code-based dependencies.

JitPack is just a stopgap rn for my needs. I'll be going through the motions for proper maven publication soon.

**Comment by JochenGuckSnk** [comment]
I already have a kotlin multiplatform publishing system based on github (https://github.com/dcxp/opentelemetry-kotlin). So i can help out create a standard Gradle project which publishes all targets, if there is interest.

**Pull request merged**
